---
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://10.0.10.10:3306/moneyplanner?autoReconnect=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: changeme
    password: changeme
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  secret: changeme
  frontend-application:
    host: localhost
    port: 8080
...
